#!/usr/bin/env python3
"""Tests for remote_validation.py — the CPV remote-execution launcher.

Regression guard for the v2.20.0 → v2.20.1 bug report:

  A user ran `/cpv-validate-local-scope` against an external project. The
  slash command invoked scripts/validate_local_scope.py from the plugin
  cache. `check_remote_execution_guard()` correctly detected remote
  execution and printed:

     Use:
       python3 …/remote_validation.py validate_local_scope /path/to/target

  But `remote_validation.py` didn't know those commands — they were
  missing from `_ALIASES` and `_COMMANDS`. Every documented invocation
  failed with "Unknown command", forcing users to set an undocumented
  CPV_REMOTE_VALIDATION=1 env var as a bypass.

  Fix: commit 2c997f5 registered `local-scope`, `project-scope`,
  `validate_local_scope`, `validate_project_scope`,
  `cpv-validate-local-scope`, `cpv-validate-project-scope` in both
  _ALIASES (so the launcher resolves them) and _COMMANDS (so the
  --help listing shows them).

This module asserts the registration contract: every alias that the
remote-execution-guard error message tells users to invoke MUST resolve
to a real script in _ALIASES.
"""

from __future__ import annotations

import sys
from pathlib import Path

# Add scripts directory to path for imports
scripts_dir = Path(__file__).resolve().parent.parent / "scripts"
if str(scripts_dir) not in sys.path:
    sys.path.insert(0, str(scripts_dir))

from remote_validation import _ALIASES, _COMMANDS  # noqa: E402


class TestScopeValidatorRegistration:
    """Every alias quoted in the remote-execution-guard error message must resolve."""

    def test_validate_local_scope_registered(self):
        """`validate_local_scope` (full script name) resolves in _ALIASES.

        This is what cpv_validation_common.py tells the user to run via:
          remote_validation.py validate_local_scope /path/to/target
        """
        assert "validate_local_scope" in _ALIASES
        assert _ALIASES["validate_local_scope"] == "validate_local_scope"

    def test_validate_project_scope_registered(self):
        """`validate_project_scope` (full script name) resolves in _ALIASES."""
        assert "validate_project_scope" in _ALIASES
        assert _ALIASES["validate_project_scope"] == "validate_project_scope"

    def test_cpv_validate_local_scope_cli_alias(self):
        """`cpv-validate-local-scope` (the installed CLI script name per pyproject.toml)
        resolves — the error message with sys.argv[0] as a .py file strips the
        suffix to form exactly this alias.
        """
        assert "cpv-validate-local-scope" in _ALIASES
        assert _ALIASES["cpv-validate-local-scope"] == "validate_local_scope"

    def test_cpv_validate_project_scope_cli_alias(self):
        """`cpv-validate-project-scope` CLI alias resolves."""
        assert "cpv-validate-project-scope" in _ALIASES
        assert _ALIASES["cpv-validate-project-scope"] == "validate_project_scope"

    def test_local_scope_short_alias(self):
        """Short-form `local-scope` resolves — matches the help-menu listing."""
        assert "local-scope" in _ALIASES
        assert _ALIASES["local-scope"] == "validate_local_scope"

    def test_project_scope_short_alias(self):
        """Short-form `project-scope` resolves."""
        assert "project-scope" in _ALIASES
        assert _ALIASES["project-scope"] == "validate_project_scope"

    def test_scope_validators_listed_in_help(self):
        """Both short aliases appear in the --help command table."""
        assert "local-scope" in _COMMANDS
        assert "project-scope" in _COMMANDS
        assert "Local scope" in _COMMANDS["local-scope"]
        assert "Project scope" in _COMMANDS["project-scope"]


class TestAliasContractWithErrorMessage:
    """The error message generated by check_remote_execution_guard() in
    cpv_validation_common.py hardcodes particular alias forms. This test
    verifies every alias that message mentions is actually registered.
    """

    def test_every_error_message_alias_is_registered(self):
        """The guard message derives `script_name.replace('.py', '')`. For
        `validate_local_scope.py` the derived alias is `validate_local_scope`,
        for `validate_project_scope.py` it's `validate_project_scope`. Both
        MUST be in _ALIASES — otherwise the user copy-pastes the suggested
        command and gets 'Unknown command'.
        """
        # Names of the .py scripts whose guard triggers on remote execution
        scope_guarded_scripts = [
            "validate_local_scope",
            "validate_project_scope",
        ]
        for alias in scope_guarded_scripts:
            assert alias in _ALIASES, (
                f"Alias {alias!r} is referenced in the guard's error message "
                f"via sys.argv[0].replace('.py', '') but is NOT registered in "
                f"_ALIASES. Users copy-pasting the suggested command will hit "
                f"'Unknown command'. Re-register in remote_validation.py."
            )


class TestAllAliasesPointToValidScripts:
    """Every _ALIASES value must name a script that exists on disk."""

    def test_every_alias_maps_to_existing_script(self):
        """Catches typos in _ALIASES values (e.g. a rename that forgot to
        update the map). Each value must be the basename (no .py extension)
        of a real scripts/*.py file.
        """
        missing: list[tuple[str, str]] = []
        for alias, target in _ALIASES.items():
            script_path = scripts_dir / f"{target}.py"
            if not script_path.exists():
                missing.append((alias, target))
        assert not missing, (
            f"The following aliases map to non-existent scripts: {missing}. "
            f"Either the script was renamed or the alias is stale."
        )


class TestCommandsDictCoherentWithAliases:
    """_COMMANDS (help text) must reference aliases that exist in _ALIASES."""

    def test_commands_help_aliases_all_resolve(self):
        """Every short alias listed in _COMMANDS (used for --help display)
        must also be present in _ALIASES so it can actually be invoked.
        """
        orphaned = [name for name in _COMMANDS if name not in _ALIASES]
        assert not orphaned, (
            f"_COMMANDS lists aliases not in _ALIASES: {orphaned}. The "
            f"launcher's --help would advertise commands that then fail with "
            f"'Unknown command'."
        )
