"""Regression tests for the render_readme_table.py link-destination escaping
defect flagged in the review of Emasoft/ai-maestro-plugins PR #18 (which ships
a byte-identical copy of this template).

`cell()` escapes `|` and newlines for table-cell TEXT, but the repository URL
from `repo_url()` was being inserted RAW into `[{name}]({url})`. Because GFM
splits a markdown table row into cells on `|` BEFORE parsing the inline link,
and a link destination ends at the first unescaped `)`, a `repository` value
containing either character truncated the link or added a spurious column.

Two-sided: an ordinary URL must render byte-identically to the pre-fix output
(captured from the render() function before the fix — see
_PRE_CHANGE_ORDINARY_OUTPUT below), otherwise every marketplace's `--check`
drift gate reddens on upgrade; a URL containing `)` / `|` / a space must stay
confined to one link inside one table cell.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPT = REPO_ROOT / "templates" / "scripts" / "render_readme_table.py"

_spec = importlib.util.spec_from_file_location("render_readme_table", SCRIPT)
assert _spec is not None and _spec.loader is not None
render_readme_table = importlib.util.module_from_spec(_spec)
sys.modules["render_readme_table"] = render_readme_table
_spec.loader.exec_module(render_readme_table)

# Captured by running `render()` against this exact fixture BEFORE the
# `_link_dest()` fix was applied (plain https://github.com URLs, with and
# without `.git`, plus a gitlab.com URL and a plugin with no repository field
# at all — the population the "byte-identical" guarantee must hold over).
_ORDINARY_PLUGINS = [
    {
        "name": "alpha",
        "version": "1.0.0",
        "category": "developer-tools",
        "description": "Alpha plugin",
        "repository": "https://github.com/owner/alpha",
    },
    {
        "name": "beta",
        "version": "2.3.1",
        "category": "security",
        "description": "Beta plugin",
        "repository": "https://github.com/owner/beta.git",
    },
    {
        "name": "gitlab-one",
        "version": "0.1.0",
        "category": "misc",
        "description": "GitLab hosted",
        "repository": "https://gitlab.com/group/sub/repo",
    },
    {
        "name": "no-repo",
        "version": "0.0.1",
        "category": "misc",
        "description": "No repo field",
    },
]

_PRE_CHANGE_ORDINARY_OUTPUT = (
    "<!-- PLUGIN-VERSIONS-START -->\n"
    "## Plugin Versions\n"
    "\n"
    "<!-- GENERATED by scripts/render_readme_table.py from "
    ".claude-plugin/marketplace.json — do not edit by hand. -->\n"
    "\n"
    "| Plugin | Version | Category | Description |\n"
    "|--------|---------|----------|-------------|\n"
    "| [alpha](https://github.com/owner/alpha) | 1.0.0 | Developer Tools "
    "| Alpha plugin |\n"
    "| [beta](https://github.com/owner/beta.git) | 2.3.1 | Security "
    "| Beta plugin |\n"
    "| [gitlab-one](https://gitlab.com/group/sub/repo) | 0.1.0 | Misc "
    "| GitLab hosted |\n"
    "| no-repo | 0.0.1 | Misc | No repo field |\n"
    "\n"
    "*4 plugins*\n"
    "\n"
    "<!-- PLUGIN-VERSIONS-END -->"
)


def test_ordinary_urls_render_byte_identically_to_pre_fix_output() -> None:
    """Plain https://github.com URLs (with/without .git), a gitlab.com URL,
    and a repo-less plugin must be untouched by the escaping fix."""
    assert render_readme_table.render(_ORDINARY_PLUGINS) == _PRE_CHANGE_ORDINARY_OUTPUT


def test_url_with_closing_paren_stays_one_link_one_cell() -> None:
    plugins = [
        {
            "name": "evil",
            "version": "1.0.0",
            "category": "x",
            "description": "d",
            "repository": "https://example.com/foo)bar",
        }
    ]
    out = render_readme_table.render(plugins)
    row = next(line for line in out.splitlines() if "evil" in line)
    # Exactly 5 pipes: the row-leading/trailing pair plus the 3 internal
    # column separators — a literal `)` in the URL must not appear unescaped,
    # and the row must still have exactly 4 columns.
    assert row.count("|") == 5
    assert ")" not in row.split("(", 1)[1].split(")")[0]
    assert "[evil](https://example.com/foo%29bar)" in out


def test_url_with_pipe_stays_one_link_one_cell() -> None:
    plugins = [
        {
            "name": "evil",
            "version": "1.0.0",
            "category": "x",
            "description": "d",
            "repository": "https://example.com/foo|bar",
        }
    ]
    out = render_readme_table.render(plugins)
    row = next(line for line in out.splitlines() if "evil" in line)
    # A raw `|` would add a 6th separator (a spurious 5th column).
    assert row.count("|") == 5
    assert "[evil](https://example.com/foo%7Cbar)" in out


def test_url_with_space_is_percent_encoded() -> None:
    plugins = [
        {
            "name": "evil",
            "version": "1.0.0",
            "category": "x",
            "description": "d",
            "repository": "https://example.com/a b",
        }
    ]
    out = render_readme_table.render(plugins)
    assert "[evil](https://example.com/a%20b)" in out


def test_url_with_embedded_newline_stays_one_row() -> None:
    """A raw newline/CR in the URL would split the table row across lines the
    same way `cell()` already guards against for plain text."""
    plugins = [
        {
            "name": "evil",
            "version": "1.0.0",
            "category": "x",
            "description": "d",
            "repository": "https://example.com/foo\nbar\r\nbaz",
        }
    ]
    out = render_readme_table.render(plugins)
    row = next(line for line in out.splitlines() if "evil" in line)
    assert row.count("|") == 5
    assert "[evil](https://example.com/foo%0Abar%0D%0Abaz)" in out


def test_already_percent_encoded_url_renders_unchanged() -> None:
    """A URL that already carries valid percent-escapes (`%20`, `%2F`) must
    not be re-encoded into a different URL — `%` is deliberately left alone."""
    plugins = [
        {
            "name": "preencoded",
            "version": "1.0.0",
            "category": "x",
            "description": "d",
            "repository": "https://example.com/a%20b/c%2Fd",
        }
    ]
    out = render_readme_table.render(plugins)
    assert "[preencoded](https://example.com/a%20b/c%2Fd)" in out


def test_url_with_literal_closing_paren_is_still_encoded() -> None:
    """The positive control for the test above: a literal `)` (which does
    need escaping to keep the link destination intact) is still encoded,
    proving the `%`-removal did not disable escaping generally."""
    plugins = [
        {
            "name": "literal-paren",
            "version": "1.0.0",
            "category": "x",
            "description": "d",
            "repository": "https://example.com/a)b",
        }
    ]
    out = render_readme_table.render(plugins)
    assert "[literal-paren](https://example.com/a%29b)" in out


def test_url_with_paren_pipe_and_space_together() -> None:
    plugins = [
        {
            "name": "evil",
            "version": "1.0.0",
            "category": "x",
            "description": "d",
            "repository": "https://example.com/a)b|c d",
        }
    ]
    out = render_readme_table.render(plugins)
    row = next(line for line in out.splitlines() if "evil" in line)
    assert row.count("|") == 5
    assert "[evil](https://example.com/a%29b%7Cc%20d)" in out
