#!/usr/bin/env python3
"""Regenerate the README plugin table from .claude-plugin/marketplace.json.

The table between the PLUGIN-VERSIONS markers is DERIVED data. Hand-maintaining
it drifts silently: the Update Submodules workflow only touches marketplace.json,
so nothing else ever rewrote the README. This script makes marketplace.json the
single source of truth for both the versions AND which plugins are listed.

Usage:
    python3 scripts/render_readme_table.py            # rewrite README.md
    python3 scripts/render_readme_table.py --check    # exit 1 if it would change

Exit codes:
    0 - README already matches (or was rewritten)
    1 - --check found drift, or an input was missing/invalid
"""

import argparse
import json
import sys
from pathlib import Path

START = "<!-- PLUGIN-VERSIONS-START -->"
END = "<!-- PLUGIN-VERSIONS-END -->"


def cell(text: str) -> str:
    """Escape a value so it cannot break out of its markdown table cell.

    A literal `|` in a description would silently add a column and shift every
    later cell, so it is escaped rather than trusted. Newlines collapse for the
    same reason.
    """
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def _link_dest(url: str) -> str:
    """Percent-encode a URL so it cannot break out of a `[text](dest)` link OR
    the table cell that link sits in.

    GFM splits a table row into cells on `|` BEFORE it parses inline markdown,
    so a literal `|` in the URL would add a spurious column even though it is
    inside `(...)`; a `)` would close the link destination early, truncating
    it; a raw newline/CR would split the row across lines the same way `cell()`
    already guards against for plain text (it collapses newlines to a space).
    Every one of these must be *encoded*, not backslash-escaped like `cell()`
    does for plain text — a backslash has no meaning inside a link destination
    and would end up as a literal character in the rendered URL. `<`/`>` are
    additionally encoded because a bare `<...>` is CommonMark autolink syntax;
    encoding them keeps the destination from ever being reinterpreted as one.
    Percent-encoding these characters is a no-op for every ordinary
    https://github.com/... URL (none of them appear), which is what keeps
    render() byte-identical for the common case and satisfies every
    marketplace's `--check` drift gate on upgrade.

    `%` is deliberately left unescaped: this function never re-scans its own
    output, so there is no double-encoding risk to guard against, and encoding
    it would corrupt any URL that already carries a valid percent-escape
    (e.g. `%20` in a pre-encoded path) into a different URL.
    """
    return (
        str(url)
        .replace("(", "%28")
        .replace(")", "%29")
        .replace("|", "%7C")
        .replace(" ", "%20")
        .replace("<", "%3C")
        .replace(">", "%3E")
        .replace("\r", "%0D")
        .replace("\n", "%0A")
    )


def repo_url(plugin: dict) -> str | None:
    """Prefer the explicit repository URL; fall back to the github source."""
    url = plugin.get("repository")
    if isinstance(url, str) and url.startswith("http"):
        return url
    src = plugin.get("source")
    if isinstance(src, dict) and src.get("source") == "github" and src.get("repo"):
        return f"https://github.com/{src['repo']}"
    return None


def render(plugins: list[dict]) -> str:
    lines = [
        START,
        "## Plugin Versions",
        "",
        "<!-- GENERATED by scripts/render_readme_table.py from .claude-plugin/marketplace.json — do not edit by hand. -->",
        "",
        "| Plugin | Version | Category | Description |",
        "|--------|---------|----------|-------------|",
    ]
    if not plugins:
        # A legitimately empty marketplace (a fresh scaffold) gets an explicit
        # placeholder row: a header with no body reads as a rendering failure, and
        # the scaffold has to pass its own --check gate on its very first run. FOUR
        # cells, because this table has four columns — the scaffolded
        # update_catalog.py uses the same wording on its own THREE-column table, and
        # copying that row verbatim would emit a malformed one here (MD056).
        lines.append("| *(no plugins yet)* | | | |")
    for p in sorted(plugins, key=lambda x: x.get("name", "")):
        name = cell(p.get("name", "?"))
        url = repo_url(p)
        label = f"[{name}]({_link_dest(url)})" if url else name
        # "developer-tools" is the manifest's slug form; the table shows prose.
        category = cell(p.get("category", "")).replace("-", " ").replace("_", " ").title()
        lines.append(
            f"| {label} | {cell(p.get('version', '?'))} | {category} | {cell(p.get('description', ''))} |"
        )
    # No generation DATE in the rendered block. The reference implementation stamped
    # date.today() here, which makes --check compare a value that changes every midnight:
    # a repo whose README was rendered yesterday fails the CI gate today on an unchanged
    # manifest. The count is derived from the manifest and is stable; git already records
    # when the table last changed.
    lines += ["", f"*{len(plugins)} plugins*", "", END]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    ap.add_argument("--check", action="store_true", help="exit 1 on drift instead of rewriting")
    args = ap.parse_args()

    mj_path = args.root / ".claude-plugin" / "marketplace.json"
    readme_path = args.root / "README.md"
    for p in (mj_path, readme_path):
        if not p.is_file():
            print(f"error: missing {p}", file=sys.stderr)
            return 1

    try:
        manifest = json.loads(mj_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as err:
        print(f"error: {mj_path} is not valid JSON: {err}", file=sys.stderr)
        return 1

    # The guard is on the manifest SHAPE, not on emptiness, and it runs first and
    # unconditionally. The hazard the old emptiness guard named — "a rendering bug
    # must not look like 'the marketplace has no plugins'" — is a MISSING or
    # wrongly-typed `plugins` key, and that is what a shape check catches, with the
    # real reason instead of a misleading one. It also covers a case emptiness never
    # reached: a TRUTHY non-list (a dict, a non-empty string) skipped the old guard
    # entirely and died in `sorted(...)` with a raw AttributeError.
    #
    # `"plugins": []` is NOT that hazard. A marketplace with no plugins genuinely has
    # no plugins, and refusing it left every fresh scaffold unable to pass the --check
    # gate it ships with.
    if not isinstance(manifest, dict):
        print(f"error: {mj_path} is a JSON {type(manifest).__name__}, expected an object", file=sys.stderr)
        return 1
    if "plugins" not in manifest:
        print(f'error: {mj_path} has no "plugins" key', file=sys.stderr)
        return 1
    plugins = manifest["plugins"]
    if not isinstance(plugins, list):
        print(f'error: "plugins" in {mj_path} is a {type(plugins).__name__}, expected a list', file=sys.stderr)
        return 1

    text = readme_path.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print(f"error: {readme_path} has no {START} / {END} markers", file=sys.stderr)
        return 1

    head, rest = text.split(START, 1)
    _, tail = rest.split(END, 1)
    updated = head + render(plugins) + tail

    if updated == text:
        print(f"README table already current ({len(plugins)} plugins)")
        return 0
    if args.check:
        print("README table is STALE — run scripts/render_readme_table.py", file=sys.stderr)
        return 1
    readme_path.write_text(updated, encoding="utf-8")
    print(f"README table regenerated ({len(plugins)} plugins)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
