#!/usr/bin/env python3
"""Generate a MICRO-agents workflow (RLM — Recursive Language Model).

EXPERIMENTAL (user directive 2026-07-22). The OPPOSITE of create_mono_agent.py:
instead of prefilling one huge agent with every skill, each skill becomes a
FOCUSED micro-agent with almost no context (just that skill + one clear input),
and a coordinator runs them as a workflow — decompose a task into an ordered
skill sequence, run each step via a fresh near-empty agent, pass output->input,
and verify each step. Small context => the pattern is more likely
"in-distribution" (better training-memory recall) and every turn is cheap.

Writes TWO artifacts into the target plugin:
  1. agents/<base>-workflow-launcher.md — a MINIMAL launcher agent whose only job
     is to call the Workflow tool with args = the task, every turn.
  2. workflows/<base>-micro-agents.ts — the Workflow-tool coordinator, templated
     with the plugin's skill palette (read at generation time). `workflows/` is a
     validator known_dirs entry, so it does not trip RC-NONSTD-DIR.

Usage:
    create_micro_agents_workflow.py <plugin-path> [--name BASE] [--include-all] [--force]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from add_component import _validate_name

# Reuse the mono-agent's plugin-slug + meta-skill classification so both
# generators agree on what "the plugin's skills" and "a meta/router skill" mean.
from create_mono_agent import _is_meta_skill, _plugin_slug


def _sanitise_slug(raw: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", raw.lower()).strip("-")
    return slug or "plugin"


def _skill_purpose(skill_md: Path) -> str:
    """The skill's one-line `description` (truncated), falling back to its name."""
    text = skill_md.read_text(encoding="utf-8")
    if text.startswith("---"):
        for line in text.splitlines()[1:]:
            if line.strip() == "---":
                break
            m = re.match(r"\s*description:\s*(.+)", line)
            if m:
                return m.group(1).strip().strip("\"'")[:140]
    return skill_md.parent.name


def build_skill_palette(plugin: Path, *, include_all: bool) -> list[dict[str, str]]:
    """The palette of skills the workflow may invoke: [{name, purpose}, ...]."""
    palette: list[dict[str, str]] = []
    for skill_md in sorted((plugin / "skills").glob("*/SKILL.md")):
        name = skill_md.parent.name
        if not include_all and _is_meta_skill(name):
            continue
        palette.append({"name": name, "purpose": _skill_purpose(skill_md)})
    return palette


# The launcher agent is deliberately MINIMAL — its whole value is the small prompt.
# `tools:` is intentionally OMITTED (→ the agent inherits all session tools,
# including Workflow + Skill) so it never fails validation on an unknown tool and
# always has the Workflow tool available at runtime.
_LAUNCHER_TEMPLATE = """---
name: {launcher_name}
description: {description}
---

# {launcher_name}

You are a thin COORDINATOR. You do NOT perform tasks yourself.

For ANY task you are given, call the **Workflow** tool with:
- `scriptPath`: `workflows/{workflow_name}.ts`
- `args`: the task description (verbatim)

The workflow decomposes the task into a sequence of skill-focused micro-agents (each
with almost no context — just one skill and one clear input), runs them, threads each
step's output into the next, and verifies each step. When it returns, relay its final
result to the user.

Do not load skills yourself and do not edit files yourself — your only job each turn is
to launch the workflow with the task as `args` and report what it returns.
"""


# The Workflow-tool coordinator. RAW string so Python leaves the JS `\\n`, backticks,
# `${...}` template literals, and `{ }` untouched; placeholders are substituted below.
_WORKFLOW_TEMPLATE = r'''// Auto-generated by cpv-create-micro-agents-workflow (EXPERIMENTAL).
// RLM (Recursive Language Model) micro-agents coordinator for the __PLUGIN_SLUG__ plugin.
//
// Each skill is run as a FOCUSED micro-agent with almost no context (just the skill
// and one clear input); this script is the COORDINATOR that decomposes the task into
// a skill sequence, runs each step via a fresh near-empty agent, threads output ->
// input, and verifies each step. Small context => the pattern is more likely
// in-distribution (better recall) and every turn is cheap.
//
// Invoked by __LAUNCHER_NAME__ (an agent whose whole job is to call this with
// args = the task). Pass the task string as `args`.

export const meta = {
  name: '__WORKFLOW_NAME__',
  description: 'RLM micro-agents coordinator for the __PLUGIN_SLUG__ plugin: decompose a task into skill-focused micro-agents, run each with minimal context, thread output into input, verify each step.',
  phases: [
    { title: 'Plan', detail: 'decompose the task into an ordered list of skills' },
    { title: 'Execute', detail: 'run each skill as a near-empty micro-agent and verify it' },
  ],
}

// The plugin's skill palette (name + one-line purpose), embedded at generation time.
const SKILLS = __SKILL_PALETTE__

const PLAN_SCHEMA = {
  type: 'object',
  properties: {
    steps: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          skill: { type: 'string', description: 'exact skill name from the palette' },
          input: { type: 'string', description: 'concrete input/instruction for this skill' },
        },
        required: ['skill', 'input'],
      },
    },
  },
  required: ['steps'],
}

const STEP_SCHEMA = {
  type: 'object',
  properties: {
    output: { type: 'string', description: 'the result of running the skill' },
    ok: { type: 'boolean', description: 'true if the skill applied cleanly' },
  },
  required: ['output', 'ok'],
}

const task = typeof args === 'string' ? args : JSON.stringify(args ?? '')
if (!task.trim()) {
  return { error: 'no task provided — pass the task as `args`' }
}

phase('Plan')
const palette = SKILLS.map(s => `- ${s.name}: ${s.purpose}`).join('\n')
const plan = await agent(
  `You are a task planner for the __PLUGIN_SLUG__ plugin. Available skills (name: purpose):\n${palette}\n\n` +
    `Decompose the task below into an ORDERED list of skill steps. Use ONLY skills from the ` +
    `palette; each step names one skill and a concrete input. Task:\n${task}`,
  { label: 'plan', phase: 'Plan', schema: PLAN_SCHEMA },
)

const steps = plan && Array.isArray(plan.steps) ? plan.steps : []
if (!steps.length) {
  return { task, plan, results: [], note: 'planner produced no steps' }
}

phase('Execute')
const results = []
let carry = '' // output of the previous step, threaded into the next
for (let i = 0; i < steps.length; i++) {
  const step = steps[i]
  const input = carry ? `${step.input}\n\nPrevious step output:\n${carry}` : step.input
  const run = await agent(
    `Invoke the skill "${step.skill}" (via the Skill tool) on this input and return ONLY its result:\n${input}`,
    { label: `run:${step.skill}`, phase: 'Execute', schema: STEP_SCHEMA },
  )
  const verify = await agent(
    `A micro-agent ran skill "${step.skill}" on:\n${input}\n\nand produced:\n${(run && run.output) || ''}\n\n` +
      `Did that satisfy the step? Judge strictly.`,
    { label: `verify:${step.skill}`, phase: 'Execute', schema: STEP_SCHEMA },
  )
  const ok = Boolean(run && run.ok) && Boolean(verify && verify.ok)
  results.push({
    skill: step.skill,
    input,
    output: (run && run.output) || '',
    ok,
    verified: Boolean(verify && verify.ok),
  })
  carry = (run && run.output) || ''
  log(`step ${i + 1}/${steps.length} ${step.skill}: ${ok ? 'ok' : 'NEEDS REVIEW'}`)
}

return { task, steps: steps.length, results, final: carry }
'''


def render_workflow_ts(plugin: Path, base: str, *, include_all: bool) -> tuple[str, str, str, int]:
    """Return (workflow_ts_text, launcher_md_text, workflow_name, skill_count)."""
    slug = _sanitise_slug(_plugin_slug(plugin))
    workflow_name = f"{base}-micro-agents"
    launcher_name = f"{base}-workflow-launcher"
    palette = build_skill_palette(plugin, include_all=include_all)
    palette_js = json.dumps(palette, indent=2)

    ts = (
        _WORKFLOW_TEMPLATE.replace("__WORKFLOW_NAME__", workflow_name)
        .replace("__LAUNCHER_NAME__", launcher_name)
        .replace("__PLUGIN_SLUG__", slug)
        .replace("__SKILL_PALETTE__", palette_js)
    )

    description = (
        f"EXPERIMENTAL RLM launcher for {slug} — for ANY task, runs the micro-agents "
        f"workflow that decomposes the task into skill-focused micro-agents (minimal "
        f"context each) and coordinates them. Use when you want skill-per-agent, "
        f"low-context execution instead of one big prefilled agent."
    )
    launcher = _LAUNCHER_TEMPLATE.format(
        launcher_name=launcher_name, description=description, workflow_name=workflow_name
    )
    return ts, launcher, workflow_name, len(palette)


def create(plugin: Path, base: str, *, include_all: bool, force: bool) -> int:
    if not (plugin / ".claude-plugin" / "plugin.json").is_file():
        print(
            f"  [create-micro-agents-workflow] {plugin}: not a plugin root (missing .claude-plugin/plugin.json)",
            file=sys.stderr,
        )
        return 1
    workflow_name = f"{base}-micro-agents"
    launcher_name = f"{base}-workflow-launcher"
    _validate_name(workflow_name, "workflow")
    _validate_name(launcher_name, "agent")

    ts, launcher, workflow_name, skill_count = render_workflow_ts(plugin, base, include_all=include_all)
    if skill_count == 0:
        print(
            f"  [create-micro-agents-workflow] {plugin}: no skills found for the palette (skills/ empty or all meta)",
            file=sys.stderr,
        )
        return 1

    ts_path = plugin / "workflows" / f"{workflow_name}.ts"
    launcher_path = plugin / "agents" / f"{launcher_name}.md"
    for path in (ts_path, launcher_path):
        if path.is_file() and not force:
            print(f"  [create-micro-agents-workflow] {path} already exists. Pass --force to overwrite.", file=sys.stderr)
            return 1

    ts_path.parent.mkdir(parents=True, exist_ok=True)
    launcher_path.parent.mkdir(parents=True, exist_ok=True)
    ts_path.write_text(ts, encoding="utf-8")
    launcher_path.write_text(launcher, encoding="utf-8")
    print(f"  [create-micro-agents-workflow] created {ts_path.relative_to(plugin)} ({skill_count} skills in palette)")
    print(f"  [create-micro-agents-workflow] created {launcher_path.relative_to(plugin)}")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("plugin_path", type=Path, help="Plugin root (containing .claude-plugin/plugin.json)")
    p.add_argument("--name", default="", help="Base name (default: plugin slug). Produces <base>-micro-agents + <base>-workflow-launcher.")
    p.add_argument(
        "--include-all",
        action="store_true",
        help="Include meta/router skills in the palette too (default: skip meta).",
    )
    p.add_argument("--force", action="store_true", help="Overwrite existing artifacts of the same name.")
    args = p.parse_args()

    plugin = args.plugin_path.resolve()
    base = args.name or _sanitise_slug(_plugin_slug(plugin))
    return create(plugin, base, include_all=args.include_all, force=args.force)


if __name__ == "__main__":
    sys.exit(main())
